### ISSUE TITLE
`git vendor list` output empty on v1.1.0

### ISSUE THREAD

**Issue by liamstask** [brettlangdon/git-vendor#4]
i have 2 vendored directories that show up as expected in `git vendor list` as of ab86ee469d8ce4c304c51d10e424fb9a3cf4c931 but _not_ as of v1.1.0 (b536c912a89f1cc8bef4617c8754e3537e4c806b)

please let me know if there's any specific info i can gather to help troubleshoot

**Comment by brettlangdon** [comment]
Hmm :( sorry about that. Thank you for reporting.

The major change I made for `v1.1.0` was to add in `git vendor remove` and to have `git vendor list` ignore listing any directories which no longer exists on disk.

Here is the commit if you are curious: https://github.com/brettlangdon/git-vendor/commit/b536c912a89f1cc8bef4617c8754e3537e4c806b

So, the problem could exist in a few places (unfortunately), when going to list out dependencies, `git-vendor` first runs through your entire git log history to find every unique `git-vendor-name:` which has a `git-vendor-dir:` which still exists on disk.

Then after it gets that list, it goes through the git log again and finds the latest commit pertaining to that `git-vendor-name: $name` dependency, and extracts the information from that.

So, there are a few things you can test manually:
1. Run the following git log command: `git log --grep="^git-vendor-name: .*\$"  --pretty=format:'START %H%n%s%n%n%b%nEND%n' HEAD`
   1. This should output all git log entries created by `git-vendor`
2. You can run this function to ensure that `git-vendor` is properly pulling out the vendored dependencies names correctly: https://github.com/brettlangdon/git-vendor/blob/baf41363096b8625f81a1c1c613ab0be91df4c09/bin/git-vendor#L41-L62
   1. If you execute the highlighted code, it'll create the function, then you should be able to just run `vendor_names_from_log`
3. Run the following git log command, but replace `$name` with the name of the vendored dependency (this is the name you assign it): `git log -1 --grep="^git-vendor-name: $name\$" --pretty=format:'START %H%n%s%n%n%b%nEND%n' HEAD`.

I am sorry that this probably isn't that much fun to debug, but knowing which of those above commands fails will help me locate where the problem lies.

**Comment by liamstask** [comment]
no worries.

`git log --grep="^git-vendor-name: .*\$" --pretty=format:'START %H%n%s%n%n%b%nEND%n' HEAD` gives happy looking output, including the git-vendor commit message for my 2 vendored deps.

`vendor_names_from_log()` successfully pulls out the user-assigned names for the deps

`git log -1 --grep="^git-vendor-name: mydep\$" --pretty=format:'START %H%n%s%n%n%b%nEND%n' HEAD` does return valid-looking output, similar to the output in step 1 but just for the dep specified.

**Comment by brettlangdon** [comment]
Ok, cool, that narrows it down quite a bit. It means that the bug exists here: https://github.com/brettlangdon/git-vendor/blob/baf41363096b8625f81a1c1c613ab0be91df4c09/bin/git-vendor#L103-L131

So, likely this crazy nested if statement: https://github.com/brettlangdon/git-vendor/blob/baf41363096b8625f81a1c1c613ab0be91df4c09/bin/git-vendor#L112-L123

Do you have the git commit message for one of the missing dependencies?

It is possible that it is not properly parsing out `git-vendor-repository` (the `[[ ! -z "$repository" ]]` check) or else something isn't right with `$showOnly`.

**Comment by liamstask** [comment]
i think the issue may be on line 101: `for name in "${vendorNames[@]}";`

this does not loop through each dep name, and appears to instead treat the expanded `vendorNames` as a single string, given the quotes around it.

if i change that to `for name in ${vendorNames[@]};`, it works as expected - not sure if that is the desired fix.

**Comment by brettlangdon** [comment]
hmm... interesting... I'll dig some more. thanks for helping me debug this!

**Comment by brettlangdon** [comment]
Yup, that appears to be the issue, since when we are iterating over it, we are getting:

```
name="dep1
dep2"
```

Instead of:

```
name="dep1"
name="dep2"
```

**Comment by liamstask** [comment]
yea - i just was not sure how the functionality that generates the contents of `${vendorNames[@]}` changed between those commits, so wasn't sure if that was the appropriate place to fix it, or if it should be addressed somewhere in `vendor_names_from_log()` possibly.

**Comment by brettlangdon** [comment]
Yeah, not sure either. I will try and sit down with this a bit more when I get home tonight.

**Comment by brettlangdon** [comment]
@liamstask I have found the problem and merged a fix into tag `v1.1.1`, I am not working on updating the homebrew formula for `git-vendor`.

**Comment by brettlangdon** [comment]
https://github.com/Homebrew/homebrew/pull/49669

**Comment by liamstask** [comment]
nice!
